const CACHE_VERSION='quran-kareem-mobile-app-v13-mobile-icons-ayah-touch-clean';
const STATIC_CACHE=`${CACHE_VERSION}-static`;
const RUNTIME_CACHE=`${CACHE_VERSION}-runtime`;
const AUDIO_CACHE=`${CACHE_VERSION}-audio`;
const APP_SHELL=['./','./index.html','./tools.html','./surah.html','./search.html','./hadith.html','./audio.html','./library.html','./settings.html','./tafsir.html','./manifest.json','./assets/css/mobile-app.css','./assets/css/qma-reviewed.css','./assets/css/qma-final-polish.css','./assets/css/qma-mobile-hard-fix.css','./assets/js/mobile-app.js','./assets/js/real-features.js','./assets/js/qma-reviewed.js','./assets/js/qma-final-polish.js','./assets/js/qma-mobile-hard-fix.js','./assets/js/pwa.js','./assets/icons/favicon-16.png','./assets/icons/favicon-32.png','./assets/icons/icon-192.png','./assets/icons/icon-512.png','./assets/icons/maskable-192.png','./assets/icons/maskable-512.png'];
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('install',event=>{event.waitUntil(caches.open(STATIC_CACHE).then(cache=>cache.addAll(APP_SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>!key.startsWith(CACHE_VERSION)).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
async function cacheFirst(request,cacheName=STATIC_CACHE){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);if(response&&(response.ok||response.type==='opaque')){const cache=await caches.open(cacheName);cache.put(request,response.clone())}return response}
async function networkFirst(request,cacheName=RUNTIME_CACHE){const cache=await caches.open(cacheName);try{const response=await fetch(request);if(response&&(response.ok||response.type==='opaque'))cache.put(request,response.clone());return response}catch(error){const cached=await cache.match(request)||await caches.match(request);if(cached)return cached;if(request.mode==='navigate')return caches.match('./surah.html')||caches.match('./index.html');throw error}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin===self.location.origin){if(/\.(css|js|json)$/i.test(url.pathname)){event.respondWith(networkFirst(request,STATIC_CACHE));return}if(/\.(png|jpg|jpeg|webp|svg|ico)$/i.test(url.pathname)){event.respondWith(cacheFirst(request,STATIC_CACHE));return}event.respondWith(networkFirst(request,RUNTIME_CACHE));return}const apiHosts=['api.alquran.cloud','api.quran-tafseer.com','api.quranpedia.net','cdn.jsdelivr.net','api.aladhan.com'];if(apiHosts.includes(url.hostname)){event.respondWith(networkFirst(request,RUNTIME_CACHE));return}const audioHosts=['cdn.islamic.network','everyayah.com','download.quranicaudio.com'];if(audioHosts.includes(url.hostname)||/\.mp3(\?|$)/i.test(url.pathname)){event.respondWith(cacheFirst(request,AUDIO_CACHE));return}});
